/**
 * SEO Configuration - Source of Truth for SkinVaults
 * This file centralizes all SEO keywords and site configuration
 */

export const PRIMARY_KEYWORDS = [
  'CS2 inventory tracker',
  'CS2 skin valuation',
  'CS2 portfolio analytics',
  'Steam skin price history',
  'CS2 investment tool',
  'cs2 skin price alerts',
  'check steam inventory value 2025',
  'best cs2 portfolio tracker',
  'safe cs2 skin analytics',
  'cs2 market trends today',
];

export const SITE_CONFIG = {
  title: "SkinVaults - The Ultimate CS2 Inventory Tracker & Skin Valuation Tool",
  description: "Track your CS2 skin portfolio with real-time analytics. Monitor price history, set alerts, and manage your Steam inventory value safely with our read-only tools.",
  url: "https://skinvaults.online",
  siteName: "SkinVaults",
};

/**
 * Extended keywords array combining primary keywords with additional SEO terms
 */
export const ALL_KEYWORDS = [
  ...PRIMARY_KEYWORDS,
  'CS2 skin analytics',
  'Counter-Strike 2 skins',
  'CS2 price tracking',
  'Steam inventory management',
  'CS2 skin portfolio',
  'skin market data',
  'CS2 skin prices',
  'inventory value tracker',
  'CS2 skin comparison',
  'skin price history',
  'CS2 investment tracking',
  'Steam skin analytics',
  'CS2 float checker',
  'CS2 skin price tracker',
  'Steam portfolio tracker',
  'CS2 market analysis',
  'skin valuation tool',
  'CS2 inventory value',
  'Steam skin prices',
  'CS2 trading analytics',
  'CS2 skins',
  'CS2 skin tracker',
  'CS2 inventory',
  'CS2 Inventory Tracker',
  'CS2 Skin Valuation',
  'CS2 Skin Prices',
  'CS2 Skin Float Value',
  'CS2 Skin Float Value Checker',
  'CS2 Skin Tracker',
  'CS2 Skin Portfolio',
  'CS2 Skin Portfolio Tracker',
  'CS2 Skin Portfolio Valuation',
  'CS2 Skin Portfolio Tracker',
  'CS2 price tracker',
  'Steam inventory',
  'CS2 skin analytics',
  'CS2 skin analytics pro',
  'CS2 premium features',
  'CS2 trading tools',
  'CS2 price alerts',
  'CS2 wishlist',
  'CS2 skin comparison',
  'CS2 skin tracker',
  'CS2 inventory',
  'CS2 price tracker',
  'Steam inventory',
  'CS2 skin analytics',
  'CS2 skin analytics pro',
  'CS2 Skin Analytics',
  'CS2 skin prices',
  'CS2 trading',
  'Counter-Strike 2 skins',
  'Counter-Strike 2',
  'Counter-Strike',
  'CSGO 2',
  'CS2',
  'CSGO',
  'CSGO 2 skins',
  'CSGO skins',
  'CS2 skin value',
  'CS2 market prices',
  'CS2 price alerts',
  'Skinvaults',
  'SkinVaults',
  'CS2 Float Value Checker', 
  'CS2 Skin Valuation',
  'CS2 Skin Tracker',
  'CS2 Skin Portfolio',
  'CS2 Skin Portfolio Tracker',
  'CS2 Skin Portfolio Valuation',
  'CS2 Skin Portfolio Tracker',
  'CS2 Skin Portfolio Tracker',
];

